# https://ci.appveyor.com/project/lektor/lektor

matrix:
  fast_finish: true

branches:
  only:
    - master

# Cache imagemagick
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml


environment:
  matrix:
    # Node 10 - Py 2.7
    - PYTHON: "C:\\Python27"
      NODE_JS_VERSION: "10"
    # Node 10 - Py 3.5
    - PYTHON: "C:\\Python35"
      NODE_JS_VERSION: "10"
    # Node 13 - Py 3.8
    - PYTHON: "C:\\Python38"
      NODE_JS_VERSION: "13"

install:
  # some tests require imagemagick
  - appveyor-retry choco install --timeout 600 imagemagick.tool || true
  - appveyor-retry choco install --timeout 600 ffmpeg || true
  - appveyor-retry choco install --timeout 600 codecov || true
  # Install lektor, dependencies and test package requirements
  - "%PYTHON%\\python.exe -m pip install --upgrade pytest"
  - "%PYTHON%\\python.exe -m pip install --upgrade codecov"
  - "%PYTHON%\\python.exe -m pip install --editable .[test]"
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:NODE_JS_VERSION
  # Install node modules
  - cd lektor\admin
  - npm install .
  - npm run webpack
  - cd ..
  - cd ..


# Not a .NET project
build: false


test_script:
  # Run Python tests
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip list"
  - "%PYTHON%\\Scripts\\pytest.exe . --tb=long -svv --cov=lektor"
  # Run JS tests
  - cd lektor\admin
  - node --version
  - npm --version
  - npm run lint
    # - npm test

after_test:
  - codecov -f "coverage.xml"

# on_failure:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
