name: Tests master

on:
  # This avoids having duplicate builds for a pull request
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ############################################################################
  # Lint jobs
  ############################################################################
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-3.9-pip-${{ hashFiles('**/setup.py') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install node dependencies
        run: cd lektor/admin && npm ci
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install python dependencies
        run: python -m pip install tox
      - name: Run pylint
        run: tox -e lint
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  ############################################################################
  # Node tests
  ############################################################################
  node:
    name: ${{ matrix.os}} node${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: ["14"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - node: "12"
            os: "ubuntu-latest"
          - node: "16"
            os: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install node dependencies
        run: cd lektor/admin && npm ci && npm run webpack
      - name: Typecheck and run frontend tests
        run: cd lektor/admin && npx tsc && npm test

  ############################################################################
  # Python tests
  ############################################################################
  python-tests:
    name: ${{ matrix.os }} py${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.6", "3.9"]
        include:
          - os: "ubuntu-latest"
            path: ~/.cache/pip
          - os: "macos-latest"
            path: ~/Library/Caches/pip
          - os: "windows-latest"
            path: ~\AppData\Local\pip\Cache
          - os: "ubuntu-latest"
            path: ~/.cache/pip
            python: "3.7"
    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-py-${{ matrix.python }}-pip-${{ hashFiles('**/setup.py') }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install macOS system dependencies
        if: startsWith(runner.os, 'macos')
        run: brew install imagemagick ffmpeg
      - name: Install Windows system dependencies
        if: startsWith(runner.os, 'windows')
        run: choco install --no-progress --timeout 600 imagemagick.tool ffmpeg
      - name: Install python dependencies
        run: python -m pip install codecov tox
      - name: Run python tests
        run: tox -e coverage
      - name: Publish coverage
        run: codecov -t 39974034-91d8-48d1-9698-de48e0667a09
